name: Deploy Infrastructure with Vault and Terraform

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    # Required for OIDC Federation with Vault
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 1. Authenticate with Vault and fetch temporary AWS Credentials
    - name: Import AWS Secrets From Vault
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ secrets.VAULT_ADDR }}         # Your ngrok URL saved in GitHub Secrets
        method: jwt
        role: github-actions-role              # The Vault JWT role we created
        secrets: |
          aws/creds/gha-s3-role access_key | AWS_ACCESS_KEY_ID ;
          aws/creds/gha-s3-role secret_key | AWS_SECRET_ACCESS_KEY

    # 2. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 3. Execute Infrastructure deployment
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve